
const students=[
      {
        "institute_id": 34,
        "email_of_institute": "7016ghsschathamattom@gmail.com",
        "institute_name": "GHSS CHATHAMATTOM (HSS)",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00034",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "Sheeja T S",
        "email_of_head": "sheejats1975@gmail.com",
        "contact_of_head": "9496092173",
        "designation_of_head": "Principal",
        "address_of_institute": "Chathamattom P. O\nPIN - 686671",
        "district_id": 7,
        "pincode": "686671",
        "local_body_id": 5621,
        "local_body_type_id": 1,
        "block_id": 16,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 69,
        "old_institute_id": "22305",
        "student_amb_det": {
          "id": 324,
          "institute_id": 34,
          "name": "Arunima Pramod",
          "email": "arunimapramod@gmail.com",
          "mobile": 7025730525,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:04:53.000000Z",
          "updated_at": "2024-06-18T11:04:53.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8696,
          "institute_id": 34,
          "name": "Amalpriya Binu",
          "email": "amalpriyabinu@gmail.com",
          "mobile": 9846221378,
          "department": "11",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:19.000000Z",
          "updated_at": "2024-06-18T11:45:19.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 7,
          "name": "Ernakulam",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "G"
        },
        "local_body": {
          "id": 5621,
          "district_id": 7,
          "local_type_id": 1,
          "name": "Paigottoor",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:34:30.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 16,
          "name": "Kothamangalam Block",
          "district_id": 7,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 69,
          "name": "KOTHAMANGALAM",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 7
        }
      },
      {
        "institute_id": 72,
        "email_of_institute": "arjunr1991@gmail.com",
        "institute_name": "Govt HSS PARAVOOR ALAPPUZHA",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00072",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "Suma A",
        "email_of_head": "govthssparavoor4111@gmail.com",
        "contact_of_head": "9061728962",
        "designation_of_head": "Principal",
        "address_of_institute": "GOVT. HIGHER SECONDARY SCHOOL PARAVOOR PUNNAPRA NORTH P.O. ALAPPUZHA -688014",
        "district_id": 4,
        "pincode": "688014",
        "local_body_id": 5539,
        "local_body_type_id": 1,
        "block_id": 10,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 36,
        "old_institute_id": "22262",
        "student_amb_det": {
          "id": 362,
          "institute_id": 72,
          "name": "Muhammed Althaf",
          "email": "gyanmaster.info@gmail.com",
          "mobile": 7012823101,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:04:57.000000Z",
          "updated_at": "2024-06-18T11:04:57.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8734,
          "institute_id": 72,
          "name": "Shamlal S",
          "email": "rafisalim9166@gmail.com",
          "mobile": 9656535319,
          "department": "Zoology",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:23.000000Z",
          "updated_at": "2024-06-18T11:45:23.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 4,
          "name": "Alappuzha",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "D"
        },
        "local_body": {
          "id": 5539,
          "district_id": 4,
          "local_type_id": 1,
          "name": "Punnapra North",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:34:19.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 10,
          "name": "Ambalapuzha Block",
          "district_id": 4,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 36,
          "name": "ALAPPUZHA",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 4
        }
      },
      {
        "institute_id": 76,
        "email_of_institute": "stdominiccemhss@yahoo.co.in",
        "institute_name": "ST DOMINICS CONVENT ENGLISH MEDIUM SCHOOL",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00076",
        "institution_category": {
          "id": 243,
          "name": "CBSE",
          "institute_type": 2,
          "finance_type": 17,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 19,
          "name": "Private Institutes",
          "institute_type": 2,
          "finance_type": 17,
          "institution_category": 243,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "SR JOISY O P ",
        "email_of_head": "srjoisyop@gmail.com",
        "contact_of_head": "8921601954",
        "designation_of_head": "PRINCIPAL",
        "address_of_institute": "ST DOMINICS CONVENT ENGLISH MEDIUM SCHOOLSREEKRISHNAPURAMPALAKKAD-679513",
        "district_id": 9,
        "pincode": "679513",
        "local_body_id": 6244,
        "local_body_type_id": 1,
        "block_id": 37,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 17,
          "name": "Private Unaided Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 19,
          "name": "CBSE",
          "institute_type": 2,
          "finance_type": 17,
          "institution_category": 243,
          "administrative_control": 19,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 8,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 98,
        "old_institute_id": "22257",
        "student_amb_det": {
          "id": 366,
          "institute_id": 76,
          "name": "NAVAMY P GOVIND",
          "email": "stdominiccemhss@yahoo.co.in",
          "mobile": 9847159398,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:04:58.000000Z",
          "updated_at": "2024-06-18T11:04:58.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8738,
          "institute_id": 76,
          "name": "SR ELSY KACHAPILLY",
          "email": "stdominiccemhss@gmail.com",
          "mobile": 8921880420,
          "department": "ENGLISH",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:23.000000Z",
          "updated_at": "2024-06-18T11:45:23.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 9,
          "name": "Palakkad",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "I"
        },
        "local_body": {
          "id": 6244,
          "district_id": 9,
          "local_type_id": 1,
          "name": "Sreekrishnapuram ",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:05.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 37,
          "name": "Sreekrishnapuram Block",
          "district_id": 9,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 8,
          "institute_type_id": 2,
          "name": "Both 1 and 2",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 98,
          "name": "CHERPULASSERY",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 9
        }
      },
      {
        "institute_id": 85,
        "email_of_institute": "pmghsspalakkad@gmail.com",
        "institute_name": "PMGHSS(hss) Palakkad",
        "registration_date": "2024-08-10",
        "student_count": 3,
        "institute_unique_id": "YIPAG00085",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "USHA V S",
        "email_of_head": "pmghsspalakkad@gmail.com",
        "contact_of_head": "9446354751",
        "designation_of_head": "Principle",
        "address_of_institute": "Victoria college road PO\nPalakkad 6786001",
        "district_id": 9,
        "pincode": "678001",
        "local_body_id": 6266,
        "local_body_type_id": 2,
        "block_id": 0,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 104,
        "old_institute_id": "22244",
        "student_amb_det": {
          "id": 375,
          "institute_id": 85,
          "name": "Karthika K",
          "email": "karthikamalu64@gmail.com",
          "mobile": 9744321919,
          "department": "S2C",
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:04:59.000000Z",
          "updated_at": "2024-08-05T08:34:25.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8747,
          "institute_id": 85,
          "name": "Baby M K",
          "email": "pmghsspalakkad@gmail.com",
          "mobile": 9605097766,
          "department": "Malayalam",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:25.000000Z",
          "updated_at": "2024-08-05T08:34:25.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 9,
          "name": "Palakkad",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "I"
        },
        "local_body": {
          "id": 6266,
          "district_id": 9,
          "local_type_id": 2,
          "name": "Palakkad (M)",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:09.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 2,
          "name": "Muncipality",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": null,
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 104,
          "name": "PALAKKAD",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 9
        }
      },
      {
        "institute_id": 105,
        "email_of_institute": "sthelensghs@gmail.com",
        "institute_name": "ST HELENS LOURDEPURAM HS Section Neyyattinkara BRC",
        "registration_date": "2024-08-10",
        "student_count": 49,
        "institute_unique_id": "YIPAG00105",
        "institution_category": {
          "id": 242,
          "name": "General",
          "institute_type": 2,
          "finance_type": 16,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 18,
          "name": "Directorate of General Education- Aided Schools",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "Sr Elsamma Thomas",
        "email_of_head": "sthelenshsstvm@gmail.com",
        "contact_of_head": "9645508444",
        "designation_of_head": "Principle",
        "address_of_institute": "ST.HELENS HS LOURDEPURAM\nKANJIRAMKULAM.P.O\npin-695524",
        "district_id": 1,
        "pincode": "695524",
        "local_body_id": 6348,
        "local_body_type_id": 1,
        "block_id": 17,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 16,
          "name": "Aided College & Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 18,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "administrative_control": 18,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 6,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 7,
        "old_institute_id": "22223",
        "student_amb_det": {
          "id": 395,
          "institute_id": 105,
          "name": "JAHANYA . J",
          "email": "sthelenshsstvm@gmail.com",
          "mobile": 9656956818,
          "department": "10",
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:02.000000Z",
          "updated_at": "2024-08-19T07:26:25.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8767,
          "institute_id": 105,
          "name": "CHITHRA.V.L",
          "email": "chithravl2000@gmail.com",
          "mobile": 9895505242,
          "department": "COMMERCE",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:27.000000Z",
          "updated_at": "2024-08-19T07:26:25.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 1,
          "name": "Thiruvananthapuram",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "A"
        },
        "local_body": {
          "id": 6348,
          "district_id": 1,
          "local_type_id": 1,
          "name": "Kanjiramkulam",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:25.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 17,
          "name": "Athiyannoor Block",
          "district_id": 1,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 6,
          "institute_type_id": 2,
          "name": "High School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 7,
          "name": "NEYYATTINKARA",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 1
        }
      },
      {
        "institute_id": 110,
        "email_of_institute": "nsshss03047@gmail.com",
        "institute_name": "NSS HSS CHOORAKKODE (HSS)",
        "registration_date": "2024-08-10",
        "student_count": 16,
        "institute_unique_id": "YIPAG00110",
        "institution_category": {
          "id": 242,
          "name": "General",
          "institute_type": 2,
          "finance_type": 16,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 18,
          "name": "Directorate of General Education- Aided Schools",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "MANJU MOHAN",
        "email_of_head": "mohanmanju482@gmail.com",
        "contact_of_head": "9446180393",
        "designation_of_head": "Principle",
        "address_of_institute": "NSS HSS CHOORAKKODE\nADOOR PIN 691551",
        "district_id": 3,
        "pincode": "691551",
        "local_body_id": 6278,
        "local_body_type_id": 1,
        "block_id": 29,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 16,
          "name": "Aided College & Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 18,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "administrative_control": 18,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 8,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 25,
        "old_institute_id": "22216",
        "student_amb_det": {
          "id": 400,
          "institute_id": 110,
          "name": "GOPIKA L",
          "email": "lathakumaris936@gmail.com",
          "mobile": 9526526356,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:02.000000Z",
          "updated_at": "2024-06-18T11:05:02.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8772,
          "institute_id": 110,
          "name": "NITYA DAVI S",
          "email": "nityadavis@gmail.com",
          "mobile": 9544156782,
          "department": "Higher Secondary",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:27.000000Z",
          "updated_at": "2024-06-18T11:45:27.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 3,
          "name": "Pathanamthitta",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "C"
        },
        "local_body": {
          "id": 6278,
          "district_id": 3,
          "local_type_id": 1,
          "name": "Erathu",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:11.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 29,
          "name": "Parakkode Block",
          "district_id": 3,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 8,
          "institute_type_id": 2,
          "name": "Both 1 and 2",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 25,
          "name": "ADOOR",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 3
        }
      },
      {
        "institute_id": 136,
        "email_of_institute": "ghsskoodal@gmail.com",
        "institute_name": "GVHSS KOODAL MURINJAKAL (HS)",
        "registration_date": "2024-08-10",
        "student_count": 30,
        "institute_unique_id": "YIPAG00136",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "Bindu S",
        "email_of_head": "ghsskoodal@gmail.com",
        "contact_of_head": "9446358165",
        "designation_of_head": "Principle",
        "address_of_institute": "GVHSS KOODAL MURINJAKAL\nPIN  689693",
        "district_id": 3,
        "pincode": "689693",
        "local_body_id": 6284,
        "local_body_type_id": 1,
        "block_id": 29,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 6,
        "sametham_id": null,
        "spark_id": "05050285",
        "brc_id": 27,
        "old_institute_id": "22181",
        "student_amb_det": {
          "id": 426,
          "institute_id": 136,
          "name": "AKSA MARY BIND SOLOMON",
          "email": "annmary267152@gmail.com",
          "mobile": 8606010210,
          "department": "9",
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:05.000000Z",
          "updated_at": "2024-08-08T05:48:49.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8798,
          "institute_id": 136,
          "name": "JAYAKUMAR R",
          "email": "rjayakumar635@gmail.com",
          "mobile": 9645512909,
          "department": "HS",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:31.000000Z",
          "updated_at": "2024-08-08T05:48:49.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 3,
          "name": "Pathanamthitta",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "C"
        },
        "local_body": {
          "id": 6284,
          "district_id": 3,
          "local_type_id": 1,
          "name": "Kalanjoor",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:12.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 29,
          "name": "Parakkode Block",
          "district_id": 3,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 6,
          "institute_type_id": 2,
          "name": "High School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 27,
          "name": "KONNI",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 3
        }
      },
      {
        "institute_id": 140,
        "email_of_institute": "aepmhss123@gmail.com",
        "institute_name": "AEPM HSS Irumpanangadu ",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00140",
        "institution_category": {
          "id": 242,
          "name": "General",
          "institute_type": 2,
          "finance_type": 16,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 18,
          "name": "Directorate of General Education- Aided Schools",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "MATHEW K ALEX",
        "email_of_head": "aepmhss123@gmail.com",
        "contact_of_head": "9447590561",
        "designation_of_head": "Principal",
        "address_of_institute": "Irumpanangadu Ezhukone PO Kollam ",
        "district_id": 2,
        "pincode": "691505",
        "local_body_id": 5854,
        "local_body_type_id": 1,
        "block_id": 52,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 16,
          "name": "Aided College & Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 18,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "administrative_control": 18,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 19,
        "old_institute_id": "22175",
        "student_amb_det": {
          "id": 430,
          "institute_id": 140,
          "name": "SREYAS S",
          "email": "aepmhss123@gmail.com",
          "mobile": 9495753897,
          "department": "Student",
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:06.000000Z",
          "updated_at": "2024-07-31T07:44:47.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8802,
          "institute_id": 140,
          "name": "RAJESWARI AMMA V K",
          "email": "rajeswarihsst@gmail.com",
          "mobile": 9495168290,
          "department": "English",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:31.000000Z",
          "updated_at": "2024-07-31T07:44:47.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 2,
          "name": "Kollam",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "B"
        },
        "local_body": {
          "id": 5854,
          "district_id": 2,
          "local_type_id": 1,
          "name": "Ezhukone ",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:34:57.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 52,
          "name": "Kottarakkara Block",
          "district_id": 2,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 19,
          "name": "Kottarakara",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 2
        }
      },
      {
        "institute_id": 154,
        "email_of_institute": "principalghsskokkur@gmail.com",
        "institute_name": "GHSS Kokkur (HSS)",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00154",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "SMITHA V",
        "email_of_head": "principalghsskokkur@gmail.com",
        "contact_of_head": "9447590018",
        "designation_of_head": "PRINCIPAL",
        "address_of_institute": "Kokkur PO Alamcode",
        "district_id": 10,
        "pincode": "679591",
        "local_body_id": 6067,
        "local_body_type_id": 1,
        "block_id": 35,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 110,
        "old_institute_id": "22158",
        "student_amb_det": {
          "id": 444,
          "institute_id": 154,
          "name": "BINDU T",
          "email": "bindutythekkan@gmail.com",
          "mobile": 9497552112,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:07.000000Z",
          "updated_at": "2024-06-18T11:05:07.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8816,
          "institute_id": 154,
          "name": "BINDU T",
          "email": "binduthekkan@gmail.com",
          "mobile": 9497552112,
          "department": " HSS",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:33.000000Z",
          "updated_at": "2024-06-18T11:45:33.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 10,
          "name": "Malappuram",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "J"
        },
        "local_body": {
          "id": 6067,
          "district_id": 10,
          "local_type_id": 1,
          "name": "ALANKODE",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:35:32.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 35,
          "name": "PERUMPADAPPU Block",
          "district_id": 10,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 110,
          "name": "EDAPPAL",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 10
        }
      },
      {
        "institute_id": 158,
        "email_of_institute": "smhsspvm@gmail.com",
        "institute_name": "St Michaels HSS Pravithanam (HS)",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00158",
        "institution_category": {
          "id": 242,
          "name": "General",
          "institute_type": 2,
          "finance_type": 16,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 18,
          "name": "Directorate of General Education- Aided Schools",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "BELLA JOSEPH",
        "email_of_head": "smhsspvm@gmail.com",
        "contact_of_head": "9946722203",
        "designation_of_head": "Principal",
        "address_of_institute": "Pravithanam P O \nPravithanam  686651",
        "district_id": 5,
        "pincode": "686651",
        "local_body_id": 5928,
        "local_body_type_id": 1,
        "block_id": 58,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 16,
          "name": "Aided College & Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 18,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "administrative_control": 18,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": "7906",
        "spark_id": "308233",
        "brc_id": 51,
        "old_institute_id": "22152",
        "student_amb_det": {
          "id": 448,
          "institute_id": 158,
          "name": "IRENE RIJO",
          "email": "irenerijo2@gmail.com",
          "mobile": 9495048145,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:08.000000Z",
          "updated_at": "2024-06-18T11:05:08.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8820,
          "institute_id": 158,
          "name": "JIJU JOSEPH",
          "email": "jijujoseph18@gmail.com",
          "mobile": 9495394039,
          "department": "EDUCATION",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:33.000000Z",
          "updated_at": "2024-06-18T11:45:33.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 5,
          "name": "Kottayam",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "E"
        },
        "local_body": {
          "id": 5928,
          "district_id": 5,
          "local_type_id": 1,
          "name": "Karoor",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:35:06.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 58,
          "name": "Lalam Block",
          "district_id": 5,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 51,
          "name": "Pala",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 5
        }
      },
      {
        "institute_id": 182,
        "email_of_institute": "anakkara9088@gmail.com",
        "institute_name": "GHSS (hss) Anakkara ",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00182",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "ANIL KUMAR A K",
        "email_of_head": "anil.a.kotteery@gmail.com",
        "contact_of_head": "9497669451",
        "designation_of_head": "Principal",
        "address_of_institute": "Anakkara Anakkara. PO Palakkad679551",
        "district_id": 9,
        "pincode": "679551",
        "local_body_id": 6179,
        "local_body_type_id": 1,
        "block_id": 22,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 0,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 108,
        "old_institute_id": "22113",
        "student_amb_det": {
          "id": 472,
          "institute_id": 182,
          "name": "NANDA P V",
          "email": "nandhavalsan@gmail.com",
          "mobile": 9539080709,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:11.000000Z",
          "updated_at": "2024-06-18T11:05:11.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8844,
          "institute_id": 182,
          "name": "Dr. JAYAPRAKASAN M V",
          "email": "jayaprakasanmv@gmail.com",
          "mobile": 9446691775,
          "department": "Science",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:36.000000Z",
          "updated_at": "2024-06-18T11:45:36.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 9,
          "name": "Palakkad",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "I"
        },
        "local_body": {
          "id": 6179,
          "district_id": 9,
          "local_type_id": 1,
          "name": "Anakkara",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:35:52.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 22,
          "name": "Thrithala Block",
          "district_id": 9,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": null,
        "brc_name": {
          "id": 108,
          "name": "THRITHALA",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 9
        }
      },
      {
        "institute_id": 197,
        "email_of_institute": "ghssarnd@gmail.com",
        "institute_name": "Govt V  HSS Aryanad (HSS Section) Nedumangad BRC",
        "registration_date": "2024-08-10",
        "student_count": 1,
        "institute_unique_id": "YIPAG00197",
        "institution_category": {
          "id": 226,
          "name": "General",
          "institute_type": 2,
          "finance_type": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 2,
          "name": "Directorate of General Education- Government Schools",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "Sucy raj A R",
        "email_of_head": "ghssarnd@gmail.com",
        "contact_of_head": "9446309355",
        "designation_of_head": "Principal",
        "address_of_institute": "Govt V HSS Aryanad\nAryanad P O",
        "district_id": 1,
        "pincode": "695125",
        "local_body_id": 6332,
        "local_body_type_id": 1,
        "block_id": 18,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 2,
          "name": "Government",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 2,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 2,
          "institution_category": 226,
          "administrative_control": 2,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": null,
        "brc_id": 6,
        "old_institute_id": "22098",
        "student_amb_det": {
          "id": 487,
          "institute_id": 197,
          "name": "Abhivad A S",
          "email": "abhivadsreejith@gmail.com",
          "mobile": 9496257176,
          "department": "plus two science",
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:13.000000Z",
          "updated_at": "2024-07-18T09:18:49.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8859,
          "institute_id": 197,
          "name": "Seena M S",
          "email": "seenacalicut1@gmail.com",
          "mobile": 9995682981,
          "department": "HSS",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:38.000000Z",
          "updated_at": "2024-07-18T09:18:49.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 1,
          "name": "Thiruvananthapuram",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "A"
        },
        "local_body": {
          "id": 6332,
          "district_id": 1,
          "local_type_id": 1,
          "name": "Aryanad",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:22.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 18,
          "name": "Vellanad Block",
          "district_id": 1,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 6,
          "name": "NEDUMANGAD",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 1
        }
      },
      {
        "institute_id": 213,
        "email_of_institute": "chsscpni@gmail.com",
        "institute_name": "CHENTRAPPINNI HSS (HSS)",
        "registration_date": "2024-08-10",
        "student_count": 38,
        "institute_unique_id": "YIPAG00213",
        "institution_category": {
          "id": 242,
          "name": "General",
          "institute_type": 2,
          "finance_type": 16,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 18,
          "name": "Directorate of General Education- Aided Schools",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "Sreejish P K",
        "email_of_head": "aidedchss@gmail.com",
        "contact_of_head": "9567929448",
        "designation_of_head": "HSST Malayalam",
        "address_of_institute": "CHENTRAPPINNI HSS SCHOOL CODE 8206 PO CHENTRAPPINNI THRISSURKERALA.",
        "district_id": 8,
        "pincode": "680687",
        "local_body_id": 6420,
        "local_body_type_id": 1,
        "block_id": 72,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 16,
          "name": "Aided College & Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 18,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "administrative_control": 18,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": "324459",
        "brc_id": 87,
        "old_institute_id": "22059",
        "student_amb_det": {
          "id": 503,
          "institute_id": 213,
          "name": "ABHIMANYU KEVIN MENOTH",
          "email": "kevinsiji@gmail.com",
          "mobile": 9961588623,
          "department": null,
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:14.000000Z",
          "updated_at": "2024-06-18T11:05:14.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8875,
          "institute_id": 213,
          "name": "Sajith V B",
          "email": "Chsscpni@gmail.com",
          "mobile": 9447832813,
          "department": "Education",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:40.000000Z",
          "updated_at": "2024-06-18T11:45:40.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 8,
          "name": "Thrissur",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "H"
        },
        "local_body": {
          "id": 6420,
          "district_id": 8,
          "local_type_id": 1,
          "name": "Edathuruthy",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:36:38.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 72,
          "name": "Mathilakam Block",
          "district_id": 8,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 87,
          "name": "MATHILAKAM",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 8
        }
      },
      {
        "institute_id": 222,
        "email_of_institute": "svhsspalemad@gmail.com",
        "institute_name": "SVHSS PALEMAD - HSS",
        "registration_date": "2024-08-10",
        "student_count": 2,
        "institute_unique_id": "YIPAG00222",
        "institution_category": {
          "id": 242,
          "name": "General",
          "institute_type": 2,
          "finance_type": 16,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "administrative_control": {
          "id": 18,
          "name": "Directorate of General Education- Aided Schools",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "name_of_head": "SANTHOSH K M",
        "email_of_head": "svhsspalemad@gmail.com",
        "contact_of_head": "9446242998",
        "designation_of_head": "Principle",
        "address_of_institute": "PALEMAD P O\nEDAKKARA",
        "district_id": 10,
        "pincode": "679331",
        "local_body_id": 6081,
        "local_body_type_id": 1,
        "block_id": 53,
        "institution_type": {
          "id": 2,
          "name": "School",
          "created_at": "2024-06-11T09:20:16.000000Z",
          "updated_at": "2024-06-11T09:20:16.000000Z",
          "deleted_at": null,
          "constant": null
        },
        "finance_type": {
          "id": 16,
          "name": "Aided College & Schools",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "institute_type": 2
        },
        "academic_control": {
          "id": 18,
          "name": "DGE",
          "institute_type": 2,
          "finance_type": 16,
          "institution_category": 242,
          "administrative_control": 18,
          "created_at": null,
          "updated_at": null,
          "deleted_at": null
        },
        "school_subcategory_id": 1,
        "sametham_id": null,
        "spark_id": "234303",
        "brc_id": 116,
        "old_institute_id": "22043",
        "student_amb_det": {
          "id": 512,
          "institute_id": 222,
          "name": "DEVANANDA T P",
          "email": "devanandatp@gmail.com",
          "mobile": 9447749407,
          "department": "Higher secondary",
          "facilitator_type": "student_ambassador",
          "created_at": "2024-06-18T11:05:16.000000Z",
          "updated_at": "2024-08-19T10:06:09.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "retired_amb_det": {
          "id": 8884,
          "institute_id": 222,
          "name": "SURESHKUMAR P",
          "email": "sureshnaduvath@gmail.com",
          "mobile": 9447537747,
          "department": "Higher Secondary",
          "facilitator_type": "retired_ambassador",
          "created_at": "2024-06-18T11:45:41.000000Z",
          "updated_at": "2024-08-19T10:06:09.000000Z",
          "deleted_at": null,
          "password": null,
          "user_type": 5,
          "status": 0
        },
        "district": {
          "id": 10,
          "name": "Malappuram",
          "created_at": null,
          "updated_at": null,
          "deleted_at": null,
          "district_code": "J"
        },
        "local_body": {
          "id": 6081,
          "district_id": 10,
          "local_type_id": 1,
          "name": "EDAKKARA",
          "created_at": "2024-05-31T08:44:28.000000Z",
          "updated_at": "2024-06-26T12:35:34.000000Z",
          "deleted_at": null,
          "block_id": null
        },
        "local_body_type": {
          "id": 1,
          "name": "Grama Panchayath",
          "created_at": "2023-12-22T07:20:29.000000Z",
          "updated_at": "2023-12-22T07:20:29.000000Z",
          "deleted_at": null
        },
        "institute_pocs": [],
        "institute_facilitator": [],
        "block": {
          "id": 53,
          "name": "NILAMBUR Block",
          "district_id": 10,
          "created_at": "2024-06-14T06:25:52.000000Z",
          "updated_at": "2024-06-14T06:25:52.000000Z",
          "deleted_at": null
        },
        "sub_category": {
          "id": 1,
          "institute_type_id": 2,
          "name": "Higher Secondary School",
          "created_at": "2024-06-14T05:46:45.000000Z",
          "updated_at": "2024-06-14T05:46:45.000000Z",
          "deleted_at": null
        },
        "brc_name": {
          "id": 116,
          "name": "NILAMBUR",
          "created_at": "2024-01-18T08:46:21.000000Z",
          "updated_at": "2024-01-18T08:46:21.000000Z",
          "deleted_at": null,
          "district_id": 10
        }}]
     
        
module.exports = students;